Repository AcademySoftwareFoundation/openexr, pull requests merged in 2020-02, with the labels that each got.

#653 fix memory leak from constructor exceptions
  OpenEXR/IlmImf/ImfScanLineInputFile.cpp
  OpenEXR/IlmImf/ImfTiledInputFile.cpp
Labels: TSC

#649 ImfChromaticities.h/cpp: Typo and pass by ref change.
  OpenEXR/IlmImf/ImfChromaticities.cpp
  OpenEXR/IlmImf/ImfChromaticities.h
Labels: Enhancement

#650 ImfAcesFile.cpp: Fix primary conversion edge case.
  OpenEXR/IlmImf/ImfAcesFile.cpp
Labels: Needs Discussion

#666 ImfChromaticities.cpp: Add back white to equality ops.
  OpenEXR/IlmImf/ImfChromaticities.cpp
Labels: Needs Discussion

#639 Split Targets and Config and add find_package
  IlmBase/config/CMakeLists.txt
  IlmBase/config/IlmBaseConfig.cmake.in
  OpenEXR/config/CMakeLists.txt
  OpenEXR/config/OpenEXRConfig.cmake.in
Labels: Needs Discussion

#672 Fix cmake install failing when install dir contains spaces, fix symlinks for shared libraries on DLL platforms
  IlmBase/config/LibraryDefine.cmake
  OpenEXR/config/LibraryDefine.cmake
Labels: Needs Discussion
